export { default as Home } from './Home/Home';
export { default as Layout } from '../components/Layout/Layout';
export { default as Login } from './Login/Login';
export { default as Profile } from './Profile/Profile';
export { default as Clases } from './Clases/Clases';
export { default as Examenes } from './Examenes/Examenes';
export { default as Servicios } from './Servicios/Servicios';
export { default as Consultas } from './Consultas/Consultas';
export { default as Alumno } from './Alumno/Alumno';
